import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { getUser } from '@/actions/auth/user.action';
import GlobalsProvider from '@/components/provider/GlobalsProvider';
import AuthHeader from '@/components/auth/AuthHeader';

const notoSansKR = Noto_Sans_KR({
  subsets: ['cyrillic', 'latin', 'latin-ext', 'vietnamese'],
  variable: '--font-notoSansKR',
});
const pretendard = localFont({
  src: '../styles/fonts/PretendardGOVVariable.woff2',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser({ serverComponent: true });
  console.log('>>user', user);

  return (
    <html
      lang="ko"
      style={{ fontSize: '16px' }}
      className={`${pretendard.variable} ${notoSansKR.variable}`}
    >
      <body className="font-pretendard">
        <GlobalsProvider initialUser={user}>
          <AuthHeader user={user} />
          {children}
        </GlobalsProvider>
      </body>
    </html>
  );
}
