import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { getUser } from '@/actions/auth/user.action';
import GlobalsProvider from '@/components/provider/GlobalsProvider';
import { HrHeader } from '@/components/common/HrHeader';
import HrNav from '@/components/common/HrNav';

const notoSansKR = Noto_Sans_KR({
  subsets: ['cyrillic', 'latin', 'latin-ext', 'vietnamese'],
  variable: '--font-notoSansKR',
});
const pretendard = localFont({
  src: '../assets/fonts/PretendardGOVVariable.woff2',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser({ serverComponent: true });

  return (
    <html
      lang="ko"
      style={{ fontSize: '16px' }}
      className={`${pretendard.variable} ${notoSansKR.variable} h-full`}
    >
      <body className="h-full flex flex-col font-pretendard">
        <div className="h-full flex flex-col min-h-0">
          {/* <GlobalsProvider initialUser={user}> */}
          <HrHeader user={user} />
          <HrNav />
          {children}
          {/* </GlobalsProvider> */}
        </div>
      </body>
    </html>
  );
}
